# Generated by Django 5.1.3 on 2024-11-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
